(evil-leader/set-key "oo" 'korg-open-dir)
(evil-leader/set-key "oa" 'org-agenda)
(evil-leader/set-key "oA" 'korg-archive-done-tasks)
(evil-leader/set-key "ot" 'korg-open-todo)
(evil-leader/set-key "on" 'korg-open-notes)
(evil-leader/set-key "oh" 'korg-open-halcom)
(evil-leader/set-key "oc" 'org-capture)
(evil-leader/set-key "oi" 'korg-open-inbox)
(evil-leader/set-key "oek" 'kris-edit-keybindings)
(evil-leader/set-key "oef" 'kris-edit-funcs)
(evil-leader/set-key "of" 'ff-find-other-file)
;; (evil-leader/set-key "ojt" 'org-jira-todo-to-jira)
;; (evil-leader/set-key "ojc" 'org-jira-create-issue)
;; (evil-leader/set-key "ojs" 'org-jira-create-subtask)
;; (evil-leader/set-key "ojp" 'org-jira-get-projects)
;; (evil-leader/set-key "ojr" 'org-jira-refresh-issue)
;; (evil-leader/set-key "ojP" 'org-jira-progress-issue)
;; (evil-leader/set-key "ojb" 'org-jira-browse-issue)
